### ISSUE TITLE
Suggestion: Get email/linkedins to contact other than developers

### ISSUE THREAD

**Issue by seraphimsakiewicz** [JustinTime42/jobs-bored#5]
Seems all of the results only return developers, but it would be neat to get back hello@ and also CEO/CTO email/linkedins.

**Comment by JustinTime42** [comment]
Thanks for the feedback!
There are two planned features that will resolve this: 
1. Finish integrating my web scraper to bring in company emails posted on their websites
2. Add the ability to query for additional key people at the company.

**Comment by JustinTime42** [comment]
These features are now integrated into the app. Thanks again for the suggestions!
