### ISSUE TITLE
Dashboard - getting error - TypeError, NextJS

### ISSUE THREAD

**Issue by JosephAlton** [JustinTime42/jobs-bored#9]
Get an error when going to dashboard:

"Application error: a client-side exception has occurred (see the browser console for more information)."

![image](https://github.com/user-attachments/assets/ef30dba4-7f96-42e2-875b-1e3782b30cb5)

browsers:
Firefox or Chrome

**Comment by JustinTime42** [comment]
Commit https://github.com/JustinTime42/jobs-bored/commit/687d34f77d97e46db9778224a1d55c8f0432ee97 should resolve this issue. @ParadigmZero can you check to make sure the issue is resolved for you. Thanks!
